# Generated by Django 4.0.4 on 2022-05-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='url',
        ),
        migrations.AddField(
            model_name='gig',
            name='added_files',
            field=models.BooleanField(default=1, help_text='Will you include source files', verbose_name='PSD/SVC Files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gig',
            name='colors_included',
            field=models.BooleanField(default=1, help_text='will you include different colors', verbose_name='Different colors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gig',
            name='delivery',
            field=models.IntegerField(default=1, help_text='number of days'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gig',
            name='mockups_included',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gig',
            name='price',
            field=models.PositiveIntegerField(default=5000, help_text='Enter price in Malawian Kwacha'),
        ),
        migrations.AddField(
            model_name='gig',
            name='quality',
            field=models.BooleanField(default=0, verbose_name='High Quality'),
            preserve_default=False,
        ),
    ]
