# Generated by Django 4.0.4 on 2022-05-31 22:26

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_remove_gig_user_gig_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Gig address'),
        ),
    ]
