# Generated by Django 4.0.4 on 2022-06-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0005_alter_gig_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='is_verified',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
