# Generated by Django 4.0.4 on 2022-06-02 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0006_gig_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='is_verified',
        ),
    ]
